---

- name: replace cobbler-s sources.list to mainline
  template:
    src: sources.list.j2
    dest: /etc/apt/sources.list

- name: add ElementaryOS ppa
  apt_repository:
    repo: "ppa:elementary-os/{{ item }}"
  with_items:
    - 'stable'
    - 'os-patches'

- name: Upgrade system
  apt:
    upgrade: full
    update_cache: yes

- name: install ElementaryOS
  apt:
    name: "elementary-desktop"
    state: present

- name: Fix cobbler-s settings of network
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces

- name: Clean Ubuntu packages
  apt:
    name: "{{ item }}"
    state: absent
  with_items:
    - 'plymouth-theme-ubuntu-text'
    - 'unity-greeter'
    - 'unity-control-center-signon'
